added file structure for flask app
MLH-Fellowship/0.5.2-cms pull request #12
Opened 2020-06-02 22:17 UTC by ebonnecab

I created a basic file structure for the flask portion of the app. Let me know if this work's for yall. It's not necessary for Flask, but I prefer to keep different types of files separated when possible

2020-06-02 22:39 UTC, amy-lei requested changes
@ebonnecab I noticed you added `my_venv/` to the `.gitignore` which is a good move(!) but it looks like all of the files in that directory still got included with this pull request. (There are 632 files to review as a result). Might have `git add`-ed too much?

2020-06-03 05:37 UTC, amy-lei commented
> @ebonnecab I noticed you added `my_venv/` to the `.gitignore` which is a good move(!) but it looks like all of the files in that directory still got included with this pull request. (There are 632 files to review as a result). Might have `git add`-ed too much?

I went and removed the files since it's a quick fix

2020-06-03 05:37 UTC, amy-lei approved these changes

2020-06-03 14:17 UTC, FawziyahAlebiosu approved these changes
Amy already fixed it so lgtm

2020-06-03 14:17 UTC, merged